reg/urls.py
from django.conf.urls import url
from reg import views
app_name="reg"
urlpatterns = [
    url("^$",views.home,name="home"),
    url("^register$",views.registration,name="register")
]

userreg/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from reg import views
urlpatterns = [
    path('admin/', admin.site.urls),
    # url('^$',views.base,name="base"),
    url("^",include("reg.urls")),

]

reg/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_url = models.URLField(blank=True)
    profile_pic = models.ImageField(blank=True)
    def __str__(self):
        return self.user.username

reg/forms.py
from django.contrib.auth.models import User
from django import forms
from reg.models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ("username","email","password")

class UserProfileForm(forms.ModelForm):
    
    class Meta:
        model = UserProfile
        exclude = ("user",)

reg/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from reg.forms import UserForm,UserProfileForm
def home(request):
    return render(request,"home.html",{})
def registration(request):
    registered = False;
    if request.method == "POST":
        user_form = UserForm(request.POST)
        user_profile = UserProfileForm(request.POST,request.FILES)
        if user_form.is_valid() and user_profile.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile=user_profile.save(commit=False)
            profile.user = user
            user_profile.save(commit=True)
            registered = True;
        else:
            print(user_form.errors,user_profile.errors)
    else:
        user_form = UserForm()
        user_profile = UserProfileForm()
    return render(request,"register.html",{'user_form':user_form,'user_profile':user_profile,'registered':registered})

reg/templates/base.html
<html>
<head>
{% load staticfiles %}
 <link rel="stylesheet" href="{% static "css\bootstrap.css" %}" />
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
    <ul class="nav navbar-nav">
       <li><a  href="{% url "reg:home" %}">HOME</a></li>
       <li><a  href="{% url "reg:register" %}">REGISTER</a></li>
       <li><a  href="{% url "admin:index" %}">ADMIN</a></li>
       {% comment %} <li><a  href="{% url 'reg:login.html' %}">LOGIN</a></li> {% endcomment %}
    </ul>
    </nav>
    <div class="container">
       {% block body_block %}
            <h1> Hello and Welcome!!!</h1>
        {% endblock %}
    </div>
    
    
</body>
</html>

reg/templates/home.html
{% extends "base.html" %}
{% block body_block %}
   <h1>Home Page</h1>
{% endblock %}

reg/templates/login.html
{% extends "base.html" %}
{% block body_block %}
   <div class="jumbotron">
       <form>
       </form>
   </div>
{% endblock %}

reg/templates/register.html
{% extends "base.html" %}
{% block body_block %}
   <div class="jumbotron">
        <form method="POST">
           {% if registered %}
              <h1>Thankyou for registering</h1>
            {% else %}
               {% csrf_token %} 
               {{user_form.as_p}}
               {{user_profile.as_p}}
               <input type="submit" class="btn btn-primary" value="Register" />
           {% endif %}
            
        </form>
   </div>
{% endblock %}